project:
  type: website
  output-dir: docs

website:
  title: "Samuel Kung"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - text: Projects
        menu: 
          - Mental-disorder-on-Media.qmd
          - Attachment-and-Exploration-in-Early-Childhood.qmd
          - English-or-Math.qmd
          - Schizophrenia-Case-Analysis.qmd
          - Stress-and-Memory-in-Students.qmd
      - text: "Resume"
        href: pdfs/resume_2025.pdf
      - icon: envelope
        href: "mailto:samuelkung0521@gmail.com"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: true

