---
title: "Samuel Kung"
about:
  template: trestles
  links:
    - text: "Resume"
      href: pdfs/resume_2025.pdf
    - icon: envelope
      text: "Email"
      href: "mailto:samuelkung0521@gmail.com"
    - icon: linkedin
      text: "LinkedIn"
      href: https://www.linkedin.com/in/samuel-kung-85a440329/
---

I am an **Honours Bachelor of Science (HBSc)** student at the **University of Toronto**, specializing in **Psychology** with a minor in **Philosophy**. My academic journey is deeply rooted in understanding human behavior, with a focus on **Social Psychology**, **Cognitive Psychology**, and **Psychopathology and Clinical Science** (DSM-V). I also have a solid foundation in **Statistics and Data Analysis**, which I leverage in my research projects.

During my professional experience as a **Children and Adolescent Social Worker Intern** at **Good Friend Mission** in Taipei, Taiwan, I:
- Interacted with and evaluated 20 social caseworks alongside senior social workers.  
- Planned and participated in 50 activities aimed at youth self-growth and life skills enhancement.  
- Gained expertise in **Adverse Childhood Experiences (ACE)**, **re-trauma prevention**, and **sensory integration techniques**.  

### Selected Academic Projects
- **Model Mental Disorder Case Vignette Evaluation**:  
  - Evaluated fictional characters using DSM-V criteria.  
  - Developed treatment suggestions and reflected on the depiction of mental disorders in media.  

- **Experiment Proposal on Attachment and Exploration in Early Childhood**:  
  - Designed a study investigating the relationship between attachment styles and exploratory behavior.  
  - Proposed data analysis techniques to predict outcomes and compared findings with existing literature.  

- **Stress and Memory in Students Study**:  
  - Conducted a study on how stress enhances or hinders memory encoding and recall in young adults.  
  - Presented results through an APA-style poster and public presentation.  

- **English and Math Proficiencies’ Influence on Statistics Attitudes**:  
  - Analyzed statistical data using descriptive statistics, t-tests, and ANOVA.  
  - Synthesized findings through Excel, hand-written calculations, and literature review.

### Skills
**Technical Skills**:  
- Proficient in **data analysis** and **APA-style writing**.  
- Experienced in **Microsoft Office** (Word, Excel, PowerPoint).  
- Fluent in **Mandarin Chinese**.  

**Soft Skills**:  
- Strong communication and critical thinking abilities.  
- Leadership and teamwork expertise, cultivated through professional and academic settings.  
- Empathetic and professional, with a focus on ethical work practices.

This combination of academic rigor and hands-on experience equips me to contribute meaningfully to the field of psychology, whether in research, clinical, or community-oriented roles.